Implement cancellation tokens
zeroc-ice/ice-demos pull request #120
Opened 2020-10-28 19:55 UTC by RedTaylor

2020-11-04 10:00 UTC, pepone requested changes
There are a few demos in IceDiscovery/Manual/Glacier2/IceStorm that need similar fixes.

2020-11-04 19:23 UTC, pepone commented on csharp/Ice/session/server/SessionFactory.cs
> +            //      current.Connection!.IdleTimeout = TimeSpan.FromSeconds(30);
you can add a TODO to remember that this need to be fixed

2020-11-04 19:24 UTC, pepone commented on csharp/Ice/invoke/server/Printer.cs
> +            CancellationToken cancel)
you should remove the empty lines here

2020-11-04 20:41 UTC, bernardnormier commented on csharp/Ice/multicast/HelloI.cs
> +    sayHello(Ice.Current current, Ice.CancellationToken cancel)
This Ice.CancellationToken does not look correct!

2020-11-10 21:40 UTC, pepone commented
There are a few demos that are still missing the cancellation token updates

* Manual\printer
* Manual\simpleFilesystem
* IceDiscovery\hello
* Glacier2\callback
* IceStorm\clock
* IceGrid\icebox\helloservice

2020-11-18 11:29 UTC, pepone reviewed
There are a couple of build errors and a few minor style issues, see comments.

2020-11-18 11:29 UTC, pepone commented on csharp/IceGrid/simple/server/Hello.cs
> +using System.Threading.Tasks;
```suggestion
using System.Threading;
```

2020-11-18 11:29 UTC, pepone commented on csharp/IceDiscovery/replication/server/Hello.cs
> +using System.Threading.Tasks;
```suggestion
using System.Threading;
```

2020-11-18 11:29 UTC, pepone commented on csharp/IceBox/hello/helloservice/HelloService.cs
>  using ZeroC.IceBox;
```suggestion
using System.Threading;
using ZeroC.Ice;
using ZeroC.IceBox;
```

2020-11-18 11:29 UTC, pepone commented on csharp/Ice/interceptor/server/Authenticator.cs
>  using ZeroC.Ice;
The using directives should be sorted alphabetically
```suggestion
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Threading;
using ZeroC.Ice;
```

2020-11-18 11:29 UTC, pepone commented on csharp/Ice/invoke/server/Printer.cs
> +using System.Threading;
Sort the using

```suggestion
using System.Threading;
using System.Threading.Tasks;
```

2020-11-18 11:29 UTC, pepone commented on csharp/Ice/plugin/helloplugin/HelloPlugin.cs
> +using System.Threading;
```suggestion
using System.Threading;
using System.Threading.Tasks;
```

2020-11-18 11:29 UTC, pepone commented on csharp/Ice/session/server/Session.cs
>  using System.Collections.Generic;
```suggestion
using System.Collections.Generic;
using System.Threading;
```

2020-11-18 11:29 UTC, pepone commented on csharp/Ice/session/server/SessionFactory.cs
> +using System.Threading.Tasks;
`using System.Threading.Tasks;` is not required

```suggestion
using System.Threading;
```

2020-11-18 11:29 UTC, pepone commented on csharp/Ice/throughput/server/Throughput.cs
>  using System.Collections.Generic;
```suggestion
using System.Collections.Generic;
using System.Threading;
```

2020-11-18 11:29 UTC, pepone commented on csharp/IceStorm/clock/subscriber/Subscriber.cs
>  using System.Diagnostics;
Sort using directives 
```suggestion
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.Threading;
```

2020-11-18 18:52 UTC, pepone approved these changes
Looks good!

2020-11-18 19:15 UTC, bernardnormier approved these changes
All good.

2020-11-18 19:15 UTC, merged